global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "saas_management-go-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "saas_management-go-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]

  # - job_name: "saas_management-go-mysql-exporter"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: [ "host.docker.internal:9104" ]
  #   metrics_path: "/metrics"         
